apiVersion: apps/v1
kind: Deployment
metadata:
  name: dderyh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dderyh
  template:
    metadata:
      labels:
        app: dderyh
    spec:
      containers:
      - image: okteto.dev/dderyh:latest
        name: dderyh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "81e9ab00-400b-4bb7-b504-32a1816914a4"
        - name: Vless_Path
          value: "/ray"
        - name: Vmess_UUID
          value: "81e9ab00-400b-4bb7-b504-32a1816914a4"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
